default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: depot
  password: depot
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: BooksDepot_development

test:
  <<: *default
  database: BooksDepot_test

production:
  <<: *default
  database: BooksDepot_production
  username: BooksDepot
  password: <%= ENV['BOOKSDEPOT_DATABASE_PASSWORD'] %>
